"use client";

import { useEffect, useRef, useState } from "react";

import { cn } from "@/lib/utils";

/**
 * The hero's moving background.
 *
 * ## The clip is our own output
 *
 * `public/marketing/hero.mp4` was generated by `scripts/generate-marketing-assets.ts`
 * using the same pinned wan-2.2 version the product runs. Licensing stock
 * footage would have been faster and it would also have been the one thing this
 * page cannot afford: a generation product whose own front page is filmed by
 * somebody else. The background is a demo.
 *
 * ## Why it does not simply autoplay
 *
 * `autoPlay` alone is a promise the browser does not keep. Chrome and Safari
 * both refuse autoplay in low-power mode, on a metered connection, and
 * sometimes for no visible reason; the returned promise rejects and the poster
 * stays. That is fine — the poster is a still of the same seed, so the fold
 * still looks composed — but it means the fade-in must be driven by `playing`,
 * not by `loadeddata`. Fading in a video that never plays leaves a frozen frame
 * pretending to be a loop.
 *
 * ## Reduced motion is respected properly
 *
 * `prefers-reduced-motion` here means "do not download or play the video at
 * all", not "play it more gently". A drifting background is exactly the class
 * of motion that triggers vestibular symptoms, and the poster carries the same
 * image. Checked in an effect rather than at module scope because it must not
 * differ between the server render and the first client render.
 *
 * ## The overlays are load-bearing
 *
 * Three of them, each doing a different job: a flat scrim so white type meets
 * contrast requirements against the brightest frame, a bottom fade so the
 * section dissolves into the page instead of ending on a hard edge, and a
 * brand-hued radial so the video reads as part of the interface rather than as
 * a rectangle behind it. Without them the headline is unreadable for about a
 * second every loop.
 */
export function HeroVideo({ className }: { className?: string }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState(false);
  const [allowed, setAllowed] = useState(false);

  /**
   * Decide whether to render a video element at all.
   *
   * `false` on the server and on the first client render, so the markup match
   * is exact and hydration cannot warn. The video is opted *into* after mount,
   * never rendered and then torn out.
   *
   * Two refusals, both of them the visitor's choice rather than ours:
   *
   *   `prefers-reduced-motion: reduce`  — a drifting full-bleed background is
   *   exactly the class of motion that triggers vestibular symptoms.
   *
   *   `navigator.connection.saveData`   — someone metering their data should
   *   not spend 2.3 MB on decoration.
   *
   * Both fall back to the poster, which carries the same frame, so the fold
   * still looks composed either way.
   */
  useEffect(() => {
    const motion = window.matchMedia("(prefers-reduced-motion: reduce)");

    const connection = (
      navigator as Navigator & {
        connection?: { saveData?: boolean; effectiveType?: string };
      }
    ).connection;

    const decide = () =>
      setAllowed(
        !motion.matches &&
          connection?.saveData !== true &&
          // 2G and slow-2G will not stream 2.3 MB usefully; the poster is the
          // better experience rather than a spinner over a blank hero.
          connection?.effectiveType !== "slow-2g" &&
          connection?.effectiveType !== "2g",
      );

    decide();
    motion.addEventListener("change", decide);
    return () => motion.removeEventListener("change", decide);
  }, []);

  useEffect(() => {
    const video = videoRef.current;
    if (!video || !allowed) return;

    // Rejects on every browser that blocks autoplay. Swallowed deliberately:
    // there is nothing to recover, and an unhandled rejection in the console
    // on first paint is noise that hides real errors.
    void video.play().catch(() => undefined);

    /**
     * Stop decoding in a background tab.
     *
     * An 8.2 s loop left running behind another tab burns battery to render
     * something nobody is looking at. `visibilitychange` is the only signal
     * that reliably covers tab switches, minimising and screen lock.
     */
    const onVisibility = () => {
      if (document.hidden) video.pause();
      else void video.play().catch(() => undefined);
    };

    document.addEventListener("visibilitychange", onVisibility);
    return () => document.removeEventListener("visibilitychange", onVisibility);
  }, [allowed]);

  return (
    <div
      aria-hidden
      className={cn("pointer-events-none absolute inset-0 -z-10", className)}
    >
      {/* The poster is a separate element rather than the video's `poster`
          attribute so it can stay behind the video and cross-fade, instead of
          being swapped out in one frame. */}
      {/**
       * `image-set()` rather than a single URL.
       *
       * This is the LCP element, and it is full-bleed: 1340x622 CSS px on a
       * desktop, ~375 wide on a phone. One asset cannot serve both without
       * wasting bandwidth at one end or resolution at the other. The 2x file is
       * 2752x1536 / 90 KB; the 1x is 1376x768 / 40 KB, so a phone on a slow
       * connection fetches a third of the bytes.
       *
       * The replaced asset was 1344x768 at 13 KB — 1x on a 2x screen and
       * compressed hard enough to be visibly soft, which is the whole of the
       * "media looks dark and low-impact" complaint. The new one has 4.2x the
       * pixels at 7x the bytes, which is the right direction for both.
       *
       * The rule lives in `styles/globals.css`, not here: the fallback for
       * browsers without `image-set()` is a second `background-image`
       * declaration, and a React style object cannot hold the same key twice.
       * Written inline it silently became two *layered* backgrounds instead.
       */}
      <div className="hero-poster absolute inset-0 bg-cover bg-center" />

      {allowed ? (
        <video
          ref={videoRef}
          // `muted` and `playsInline` are both required for autoplay to be
          // permitted at all; `playsInline` specifically stops iOS Safari
          // taking the video fullscreen the moment it starts.
          muted
          loop
          playsInline
          autoPlay
          /**
           * `none`, not `auto`.
           *
           * This is decoration behind a headline, and `auto` had it competing
           * for bandwidth with the LCP element it sits under. The effect only
           * runs after `play()` is called in the effect below, which is after
           * paint — so nothing is lost except the head start it was taking
           * from the text.
           */
          preload="none"
          onPlaying={() => setPlaying(true)}
          className={cn(
            "absolute inset-0 size-full object-cover transition-opacity duration-1000 ease-out",
            playing ? "opacity-100" : "opacity-0",
          )}
        >
          {/* WebM first: VP9 encodes this loop at 2,307 KB against H.264's
              2,865 KB — a 19% saving for every browser that accepts it, which
              is all of them except Safari. The browser picks the first source
              it can play and downloads only that one, so ordering *is* the
              negotiation and no visitor fetches both. */}
          <source src="/marketing/hero.webm" type="video/webm" />
          <source src="/marketing/hero.mp4" type="video/mp4" />
        </video>
      ) : null}

      {/**
       * One scrim, not three.
       *
       * This was a flat `bg-background/70`, then a `from-background/60` gradient
       * over it, then a brand tint at 60%. Compounded, the top of the frame was
       * about 88% obscured — the artwork behind it was effectively invisible,
       * and the hero read as a dark rectangle with a headline on it. That is
       * the "too dark and muddy" complaint, and it was three decisions each
       * reasonable on its own.
       *
       * The replacement is a single vertical gradient: light where the art is,
       * heavy at the bottom where the section has to dissolve into the page.
       * The headline sits in the upper third against roughly 40% rather than
       * 88%, which is still a contrast floor — Lighthouse's contrast audit is
       * the check, and it stays at 100.
       */}
      <div className="absolute inset-0 bg-gradient-to-b from-background/40 via-background/45 to-background" />

      {/* Ties the rectangle to the brand. Halved: at 60% it was doing as much
          obscuring as tinting. */}
      <div className="absolute inset-0 bg-gradient-brand-subtle opacity-30" />
    </div>
  );
}
