import "server-only";

// Generated by scripts/build-gallery-media.mjs. Do not edit by hand.
//
// Which model produced each published card. Server-only on purpose — see the
// note in the build script. Checked by services/marketing/publication-policy.ts.

export const GALLERY_SOURCE_MODELS: Readonly<Record<string, string>> = {
  "paper-boat-street": "replicate/video-gen",
  "coast-drive": "replicate/video-gen",
  "dragon-modern": "replicate/video-gen",
  "coffee-dawn": "replicate/video-gen",
};
