import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { ShotPlanPreview } from "@/features/studio/components/shot-plan";
import type { ProviderShotSupport } from "@/services/ai/video-director";

/** Both models Atheos ships today: one clip, no audio, no shot list. */
const CURRENT_PROVIDER: ProviderShotSupport = {
  supportsMultiShot: false,
  supportsNegativePrompt: true,
  supportsNativeAudio: false,
  maxDurationSeconds: 10,
};

/** A hypothetical future model, to prove the panel is not hardcoded. */
const CAPABLE_PROVIDER: ProviderShotSupport = {
  supportsMultiShot: true,
  supportsNegativePrompt: true,
  supportsNativeAudio: true,
  maxDurationSeconds: 10,
};

const CINEMATIC_ES =
  "video cinematográfico del carro rojo desde el cielo, de todos los ángulos, con audio";

describe("the shot-plan preview", () => {
  it("shows nothing for an empty prompt", () => {
    // A panel of defaults over an empty field reads as the product having
    // already decided what to make.
    const { container } = render(
      <ShotPlanPreview
        prompt="   "
        durationSeconds={10}
        provider={CURRENT_PROVIDER}
      />,
    );
    expect(container.innerHTML).toBe("");
  });

  it("states the duration and the shot count", () => {
    render(
      <ShotPlanPreview
        prompt={CINEMATIC_ES}
        durationSeconds={10}
        provider={CAPABLE_PROVIDER}
      />,
    );
    expect(screen.getByText(/10 seconds/)).toBeTruthy();
    expect(screen.getByText(/4 shots/)).toBeTruthy();
  });

  it("says plainly that this model will only generate the first shot", () => {
    /**
     * The whole reason the panel exists. A confident four-shot list rendered
     * over a provider that returns one clip is a promise the generation cannot
     * keep, and the user pays either way.
     */
    render(
      <ShotPlanPreview
        prompt={CINEMATIC_ES}
        durationSeconds={10}
        provider={CURRENT_PROVIDER}
      />,
    );
    expect(screen.getByText(/returns one continuous clip/)).toBeTruthy();
    expect(screen.getByText(/one generation per shot/)).toBeTruthy();
  });

  it("lists only the shot that will actually be generated", () => {
    // Listing four while warning that one will be made is still a four-shot
    // promise with a caveat attached.
    render(
      <ShotPlanPreview
        prompt={CINEMATIC_ES}
        durationSeconds={10}
        provider={CURRENT_PROVIDER}
      />,
    );
    expect(screen.getAllByRole("listitem")).toHaveLength(1);
  });

  it("lists every shot when the provider can take them", () => {
    render(
      <ShotPlanPreview
        prompt={CINEMATIC_ES}
        durationSeconds={10}
        provider={CAPABLE_PROVIDER}
      />,
    );
    expect(screen.getAllByRole("listitem")).toHaveLength(4);
    expect(screen.queryByText(/one continuous clip/)).toBeNull();
  });

  it("names Atheos as the source of the sound, not the model", () => {
    render(
      <ShotPlanPreview
        prompt={CINEMATIC_ES}
        durationSeconds={10}
        provider={CURRENT_PROVIDER}
      />,
    );
    expect(screen.getByText(/Soundscape added by Atheos/)).toBeTruthy();
    // The claim that would be false on every model currently shipped.
    expect(screen.queryByText(/generated by the video model/)).toBeNull();
  });

  it("credits the model when the model really did make the audio", () => {
    render(
      <ShotPlanPreview
        prompt={CINEMATIC_ES}
        durationSeconds={10}
        provider={CAPABLE_PROVIDER}
      />,
    );
    expect(screen.getByText(/Audio generated by the video model/)).toBeTruthy();
  });

  it("says 'No audio' when none was asked for, and plans one shot", () => {
    render(
      <ShotPlanPreview
        prompt="un carro rojo en la carretera de la costa"
        durationSeconds={5}
        provider={CURRENT_PROVIDER}
      />,
    );
    expect(screen.getByText("No audio")).toBeTruthy();
    // No cut was requested, so none is planned — and nothing is collapsed.
    expect(screen.getByText(/1 shot/)).toBeTruthy();
    expect(screen.queryByText(/one continuous clip/)).toBeNull();
  });

  it("shows timings inside the requested duration", () => {
    render(
      <ShotPlanPreview
        prompt={CINEMATIC_ES}
        durationSeconds={10}
        provider={CAPABLE_PROVIDER}
      />,
    );
    const items = screen.getAllByRole("listitem");
    expect(items[0].textContent).toMatch(/^0\.0–/);
    expect(items[3].textContent).toMatch(/–10\.0s/);
  });
});
