/**
 * Generate the marketing site's imagery with the product's own models.
 *
 *   npx dotenv-cli -e .env.local -- npx tsx scripts/generate-marketing-assets.ts
 *   npx dotenv-cli -e .env.local -- npx tsx scripts/generate-marketing-assets.ts hero
 *
 * ## Why generate rather than buy stock
 *
 * Atheos sells image and video generation. A landing page for it decorated
 * with Pexels footage is making a claim it is simultaneously disproving, and
 * the first visitor who reverse-image-searches the hero finds that out. Every
 * asset here comes from the **same pinned model versions the product runs** —
 * so the page is a demo, not a mock-up, and the caption under a gallery tile
 * is literally the prompt that produced it.
 *
 * ## Cost
 *
 * Real money, on the live Replicate account. At measured rates an image is
 * about $0.003 and five seconds of 720p video about $0.10, so a full run is
 * well under a dollar. Outputs are committed to `public/marketing/`, so this
 * script runs when the imagery should change and never on a build.
 *
 * ## WebM is encoded by hand, afterwards
 *
 * Replicate returns H.264 only. The site serves a VP9/WebM alternate first —
 * 720 KB against 1,310 KB for the hero — so after regenerating a video, run:
 *
 *   ffmpeg -i public/marketing/hero.mp4 -c:v libvpx-vp9 -crf 34 -b:v 0  *     -row-mt 1 -an public/marketing/hero.webm
 *
 * Skipping it is not fatal: the browser falls through to the MP4 `<source>`.
 * It just costs every non-Safari visitor an extra 590 KB.
 *
 * ## Determinism
 *
 * Every request carries an explicit seed. Re-running reproduces the same
 * images rather than quietly redecorating the site, and a single tile can be
 * regenerated by changing one seed.
 */

import { createWriteStream, existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import path from "node:path";

const TOKEN = process.env.REPLICATE_API_TOKEN;
const OUT = path.join(process.cwd(), "public", "marketing");

/** Pinned to match services/ai/providers/replicate.ts exactly. */
const FLUX_SCHNELL =
  "c846a69991daf4c0e5d016514849d14ee5b2e6846ce6b9d6f21369e564cfe51e";
const WAN_VIDEO =
  "c483b1f7b892065bc58ebadb6381abf557f6b1f517d2ff0febb3fb635cf49b4d";

/**
 * A house look, appended to every image prompt.
 *
 * The gallery is eight tiles seen together; without a shared grade they read
 * as eight unrelated stock photos rather than as one product's output. Dark
 * and violet-leaning because that is the interface they sit inside — a bright
 * image on this page looks like a hole cut in the page.
 */
const HOUSE =
  "deep black background, violet and magenta accent light, high contrast, " +
  "cinematic colour grade, fine grain, no text, no watermark, no logo";

interface ImageJob {
  name: string;
  prompt: string;
  seed: number;
  aspect: string;
}

/** Matches the GALLERY captions in features/marketing/i18n/en.ts, in order. */
const GALLERY: ImageJob[] = [
  {
    name: "gallery-1",
    prompt: "Volumetric light through fog, anamorphic lens flare",
    seed: 11,
    aspect: "1:1",
  },
  {
    name: "gallery-2",
    prompt: "Liquid chrome sculpture, studio reflection",
    seed: 27,
    aspect: "1:1",
  },
  {
    name: "gallery-3",
    prompt: "Aurora over black water, long exposure",
    seed: 43,
    aspect: "1:1",
  },
  {
    name: "gallery-4",
    prompt: "Neon rain on glass, shallow depth of field",
    seed: 58,
    aspect: "1:1",
  },
  {
    name: "gallery-5",
    prompt: "Isometric city at dusk, miniature tilt shift",
    seed: 71,
    aspect: "1:1",
  },
  {
    name: "gallery-6",
    prompt: "Solar flare, extreme macro detail",
    seed: 89,
    aspect: "1:1",
  },
  {
    name: "gallery-7",
    prompt: "Deep space nebula, true blacks",
    seed: 97,
    aspect: "1:1",
  },
  {
    name: "gallery-8",
    prompt: "Bioluminescent jellyfish, underwater",
    seed: 103,
    aspect: "1:1",
  },
];

/** Matches the TEMPLATES entries, in order. */
const TEMPLATES: ImageJob[] = [
  {
    name: "template-1",
    prompt:
      "A matte black perfume bottle on a seamless backdrop, studio lighting, controlled reflections, product photography",
    seed: 211,
    aspect: "4:3",
  },
  {
    name: "template-2",
    prompt:
      "Cinematic film still, lone figure in a corridor, anamorphic framing, practical light, shallow depth of field",
    seed: 223,
    aspect: "4:3",
  },
  {
    name: "template-3",
    prompt:
      "Editorial portrait, soft key light, rim separation, neutral colour science, magazine cover quality",
    seed: 233,
    aspect: "4:3",
  },
  {
    name: "template-4",
    prompt:
      "Isometric illustration of a small workshop, clean geometry, flat palette, consistent light angle",
    seed: 241,
    aspect: "4:3",
  },
  {
    name: "template-5",
    prompt:
      "Abstract looping motion graphic, flowing ribbons of light, seamless cycle",
    seed: 251,
    aspect: "4:3",
  },
  {
    name: "template-6",
    prompt:
      "A studio microphone in a darkened recording booth, warm rim light, calm and unhurried",
    seed: 263,
    aspect: "4:3",
  },
];

/**
 * The two wide feature cards.
 *
 * Only the wide ones. Six images across six cards reads as a stock-photo grid
 * and buries the words; two, on the cards that are twice the width and were
 * otherwise mostly empty, gives the section a rhythm instead of a texture.
 *
 * Deliberately abstract — an illustration of "one library for everything"
 * that shows a literal library is worse than one that shows nothing.
 */
const FEATURES: ImageJob[] = [
  {
    name: "feature-library",
    prompt:
      "Countless small glowing panes of light arranged in a vast ordered archive receding into darkness, one continuous structure",
    seed: 401,
    aspect: "16:9",
  },
  {
    name: "feature-craft",
    prompt:
      "A dark workspace lit by a single screen, calm and precise, long working hours, cinematic",
    seed: 409,
    aspect: "16:9",
  },
];

/** The three modality tabs. */
const SHOWCASE: ImageJob[] = [
  {
    name: "showcase-image",
    prompt:
      "A crystalline prism splitting light into colour, macro, museum lighting",
    seed: 303,
    aspect: "4:3",
  },
  {
    name: "showcase-video",
    prompt:
      "Motion-blurred streaks of light through a dark tunnel, long exposure, sense of travel",
    seed: 237,
    aspect: "4:3",
  },
  {
    name: "showcase-audio",
    prompt:
      "A three-dimensional waveform of glowing filaments suspended in darkness",
    seed: 162,
    aspect: "4:3",
  },
];

/**
 * The hero background.
 *
 * Constraints that matter more than the subject: **dark**, because white
 * headline type sits on top of it, and **slow**, because fast motion behind
 * text is unreadable and makes people leave. No hard cuts and no recognisable
 * subject — the eye should register atmosphere and then go to the words.
 */
const HERO = {
  name: "hero",
  prompt:
    "Slow drifting particles of violet and magenta light in deep black space, " +
    "soft volumetric haze, gentle continuous flow, no camera cuts, " +
    "abstract, cinematic, dark, unhurried",
  seed: 7,
};

/**
 * The sign-in and sign-up panel.
 *
 * Portrait, because the panel is a tall column beside the form rather than a
 * banner above it. Darker and slower even than the hero: this one sits next to
 * input fields, and motion beside a field somebody is typing into is the kind
 * that gets a product called distracting.
 */
const AUTH = {
  name: "auth",
  prompt:
    "Slow vertical drift of violet and magenta light through deep black space, " +
    "soft volumetric haze, gentle continuous upward flow, no camera cuts, " +
    "abstract, cinematic, very dark, unhurried",
  seed: 21,
};

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * Replicate throttles hard when the account balance is low — six predictions a
 * minute, burst of one, below $5 of credit. That is not an error condition, it
 * is the documented behaviour, so it is retried rather than reported. The API
 * returns `retry_after` in seconds; a second of slack on top covers clock skew
 * between us and them.
 */
async function submit(version: string, input: Record<string, unknown>) {
  for (let attempt = 0; attempt < 8; attempt += 1) {
    const response = await fetch("https://api.replicate.com/v1/predictions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${TOKEN}`,
        "Content-Type": "application/json",
        Prefer: "wait=60",
      },
      body: JSON.stringify({ version, input }),
    });

    if (response.status !== 429) return response;

    const body = (await response.json()) as { retry_after?: number };
    await sleep(((body.retry_after ?? 10) + 1) * 1000);
  }
  throw new Error("still throttled after 8 attempts");
}

async function replicate(version: string, input: Record<string, unknown>) {
  const start = await submit(version, input);

  if (!start.ok) {
    throw new Error(`${start.status} ${await start.text()}`);
  }

  let prediction = (await start.json()) as {
    id: string;
    status: string;
    output?: unknown;
    error?: string;
    urls: { get: string };
  };

  // `Prefer: wait` returns early for anything slower than a minute, which is
  // every video and some images. Poll from there.
  while (["starting", "processing"].includes(prediction.status)) {
    await sleep(3000);
    const poll = await fetch(prediction.urls.get, {
      headers: { Authorization: `Bearer ${TOKEN}` },
    });
    prediction = await poll.json();
  }

  if (prediction.status !== "succeeded") {
    throw new Error(`${prediction.status}: ${prediction.error ?? "no output"}`);
  }

  const output = prediction.output;
  const url = Array.isArray(output) ? output[0] : output;
  if (typeof url !== "string") {
    throw new Error(`unexpected output shape: ${JSON.stringify(output)}`);
  }
  return url;
}

async function download(url: string, file: string) {
  const response = await fetch(url);
  if (!response.ok || !response.body) {
    throw new Error(`download failed: ${response.status}`);
  }
  await pipeline(
    Readable.fromWeb(response.body as never),
    createWriteStream(file),
  );
}

async function runImages(jobs: ImageJob[]) {
  const manifest: Record<string, string> = {};

  for (const job of jobs) {
    const file = path.join(OUT, `${job.name}.webp`);

    // Already on disk. These are committed assets, so a re-run after a
    // throttled batch should fill the gaps rather than pay for the whole set
    // again — and rerunning must not silently redecorate tiles that are fine.
    if (existsSync(file)) {
      manifest[job.name] = job.prompt;
      console.log(`${job.name} … cached`);
      continue;
    }

    process.stdout.write(`${job.name} … `);
    try {
      const url = await replicate(FLUX_SCHNELL, {
        prompt: `${job.prompt}. ${HOUSE}`,
        aspect_ratio: job.aspect,
        output_format: "webp",
        // 90 rather than the default 80: these are hero-adjacent and the extra
        // few kilobytes are cheaper than visible banding on a dark gradient.
        output_quality: 90,
        num_outputs: 1,
        seed: job.seed,
      });
      await download(url, file);
      manifest[job.name] = job.prompt;
      console.log("ok");
    } catch (error) {
      console.log(`FAILED — ${error instanceof Error ? error.message : error}`);
    }
  }

  return manifest;
}

async function runAuth() {
  const file = path.join(OUT, "auth.mp4");
  if (existsSync(file)) {
    console.log("auth video … cached");
    return;
  }

  process.stdout.write("auth video … ");
  const url = await replicate(WAN_VIDEO, {
    prompt: AUTH.prompt,
    num_frames: 81,
    aspect_ratio: "9:16",
    resolution: "720p",
    seed: AUTH.seed,
  });
  await download(url, file);
  console.log("ok");

  process.stdout.write("auth poster … ");
  const poster = await replicate(FLUX_SCHNELL, {
    prompt: `${AUTH.prompt}. ${HOUSE}`,
    aspect_ratio: "9:16",
    output_format: "webp",
    output_quality: 85,
    num_outputs: 1,
    seed: AUTH.seed,
  });
  await download(poster, path.join(OUT, "auth-poster.webp"));
  console.log("ok");
}

async function runHero() {
  if (existsSync(path.join(OUT, "hero.mp4"))) {
    console.log("hero video … cached");
    return;
  }

  process.stdout.write("hero video … ");
  const url = await replicate(WAN_VIDEO, {
    prompt: HERO.prompt,
    num_frames: 81, // 5s at 16fps — the model's floor, and the cheapest loop.
    aspect_ratio: "16:9",
    resolution: "720p",
    seed: HERO.seed,
  });
  await download(url, path.join(OUT, "hero.mp4"));
  console.log("ok");

  // A still from the same seed, used as the video's poster so the fold is not
  // empty while several megabytes of MP4 arrive.
  process.stdout.write("hero poster … ");
  const poster = await replicate(FLUX_SCHNELL, {
    prompt: `${HERO.prompt}. ${HOUSE}`,
    aspect_ratio: "16:9",
    output_format: "webp",
    output_quality: 85,
    num_outputs: 1,
    seed: HERO.seed,
  });
  await download(poster, path.join(OUT, "hero-poster.webp"));
  console.log("ok");
}

async function main() {
  if (!TOKEN) throw new Error("REPLICATE_API_TOKEN is not set");
  await mkdir(OUT, { recursive: true });

  const only = process.argv[2];
  const manifest: Record<string, string> = {};

  if (!only || only === "hero") await runHero();
  if (!only || only === "auth") await runAuth();
  if (!only || only === "images") {
    Object.assign(
      manifest,
      await runImages([...GALLERY, ...TEMPLATES, ...SHOWCASE, ...FEATURES]),
    );
  }

  if (Object.keys(manifest).length > 0) {
    // Written so the page can state what produced each tile. An AI product
    // showing generated work without the prompt is asking to be doubted.
    await writeFile(
      path.join(OUT, "prompts.json"),
      JSON.stringify(manifest, null, 2) + "\n",
      "utf8",
    );
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
