// Generated by scripts/build-gallery-media.mjs. Do not edit by hand.
//
// Every entry is derived from a master in `media-source/`: the dimensions are
// probed, the filenames carry the master's content hash, and the prompt is the
// one that produced it. Re-run the script after changing
// `media-source/gallery-selection.json`.

export interface GalleryItem {
  /** Stable slug. Also the filename stem, so it must stay unique. */
  id: string;
  kind: "image" | "video";
  /** Shown on the card, and the label the filters group by. */
  category: string;
  /** The prompt that made it. Shown under the card. */
  prompt: string;
  /** What "Try this" opens the studio in. */
  modality: "IMAGE" | "VIDEO";
  /** The master's real pixels, used for the aspect box so nothing shifts. */
  width: number;
  height: number;
  /** 1280w WebP. `next/image` resizes down from this for smaller cards. */
  poster: string;
  /** Videos only. Loaded on interaction, never before. */
  src?: string;
  /** The master this was derived from, recorded in docs/GALLERY-PROVENANCE.md. */
  masterSha256: string;
}

export const GALLERY: readonly GalleryItem[] = [
  {
    id: "paint-ridges",
    kind: "image",
    category: "Abstract",
    prompt:
      "Thick oil paint in ochre and deep teal pushed across a panel, raking light picking up the ridges",
    modality: "IMAGE",
    width: 2048,
    height: 2048,
    poster: "/marketing/gallery/paint-ridges-1280.2fbb74c716.webp",
    masterSha256:
      "2fbb74c7166ee5813e5cc30b559d54f2d676a88c625cd9cf053915ac66a6aabb",
  },
  {
    id: "light-trails",
    kind: "image",
    category: "Abstract",
    prompt:
      "Long-exposure light trails folding through smoke, warm amber against near-black",
    modality: "IMAGE",
    width: 2752,
    height: 1536,
    poster: "/marketing/gallery/light-trails-1280.aefed29423.webp",
    masterSha256:
      "aefed2942384eaf3621c75a2f02736164b5508c7d6e0074204244ac128a4431c",
  },
  {
    id: "concrete-stair",
    kind: "image",
    category: "Architecture",
    prompt:
      "A brutalist concrete stairwell lit by a single skylight, geometric shadow, warm grey tones",
    modality: "IMAGE",
    width: 2528,
    height: 1696,
    poster: "/marketing/gallery/concrete-stair-1280.c516790495.webp",
    masterSha256:
      "c51679049521df7e01ff075c6682102305074dc3d9e20383dd2c7047e10b1a70",
  },
  {
    id: "glass-atrium",
    kind: "image",
    category: "Architecture",
    prompt:
      "A glass atrium at golden hour seen from below, steel lattice ceiling, long diagonal light",
    modality: "IMAGE",
    width: 2752,
    height: 1536,
    poster: "/marketing/gallery/glass-atrium-1280.a3445180a5.webp",
    masterSha256:
      "a3445180a53fda7c3de1f4661beb6bedc5338bed3980825717d90c6f966820ae",
  },
  {
    id: "cream-coat",
    kind: "image",
    category: "Fashion",
    prompt:
      "A model in a structured cream coat against a sunlit concrete wall, hard midday shadow",
    modality: "IMAGE",
    width: 1792,
    height: 2400,
    poster: "/marketing/gallery/cream-coat-1280.fbc0a24f87.webp",
    masterSha256:
      "fbc0a24f8700191d67cb97a9590f60c5ddc0b9d042f3f2c784baacf2d794ce3f",
  },
  {
    id: "scarlet-silk",
    kind: "image",
    category: "Fashion",
    prompt:
      "Flowing scarlet silk caught mid-air in a studio, black background, single hard light",
    modality: "IMAGE",
    width: 1696,
    height: 2528,
    poster: "/marketing/gallery/scarlet-silk-1280.fc39da8d5b.webp",
    masterSha256:
      "fc39da8d5ba39c7ccb5a5fabcd3325b4b7c17c9b9b32f44f59f0ca76659539b0",
  },
  {
    id: "halved-fig",
    kind: "image",
    category: "Food",
    prompt:
      "A halved fig on a linen cloth, late afternoon light, warm shadow, shot from just above",
    modality: "IMAGE",
    width: 2400,
    height: 1792,
    poster: "/marketing/gallery/halved-fig-1280.09a81c4d2e.webp",
    masterSha256:
      "09a81c4d2eca39a20a25581487aba0f882d030c101256dcc29da126e61b79946",
  },
  {
    id: "pine-mist",
    kind: "image",
    category: "Nature",
    prompt:
      "Mist moving through an old pine forest at first light, cool blue shadows, shafts of sun",
    modality: "IMAGE",
    width: 2752,
    height: 1536,
    poster: "/marketing/gallery/pine-mist-1280.d341924291.webp",
    masterSha256:
      "d3419242911ba80a1b4ec9a5f8d06f3b758f04b45d1fecb4b363433290b5b192",
  },
  {
    id: "white-poppy",
    kind: "image",
    category: "Nature",
    prompt:
      "A single white poppy in close focus against a green field gone soft, morning dew",
    modality: "IMAGE",
    width: 2528,
    height: 1696,
    poster: "/marketing/gallery/white-poppy-1280.8a0c6e2d99.webp",
    masterSha256:
      "8a0c6e2d99975b5a1ed3ba0a8e298c917a4f6f40ec8b756ae00a509e7602b063",
  },
  {
    id: "silver-hair",
    kind: "image",
    category: "Portrait",
    prompt:
      "An editorial portrait of an older woman with silver hair, soft window light from the left",
    modality: "IMAGE",
    width: 2400,
    height: 1792,
    poster: "/marketing/gallery/silver-hair-1280.66ad24332e.webp",
    masterSha256:
      "66ad24332e110231ea4784a0e8112919aff4b94c02ea50b64c340f813d1149e6",
  },
  {
    id: "knitted-collar",
    kind: "image",
    category: "Portrait",
    prompt:
      "A close portrait of a young man in a knitted collar, overcast daylight, muted greens",
    modality: "IMAGE",
    width: 1792,
    height: 2400,
    poster: "/marketing/gallery/knitted-collar-1280.3dcff7b46b.webp",
    masterSha256:
      "3dcff7b46bc772d0f8c4db4dfef10dab0ccca28db727ce87ced5c4764f261058",
  },
  {
    id: "titanium-watch",
    kind: "image",
    category: "Product",
    prompt:
      "A brushed titanium watch on a slab of pale stone, studio softbox, controlled reflections",
    modality: "IMAGE",
    width: 2048,
    height: 2048,
    poster: "/marketing/gallery/titanium-watch-1280.1fb8ce9fe2.webp",
    masterSha256:
      "1fb8ce9fe2ba865aed984b8f5281ace7c693f338578851d8e3702db3be5c0d9f",
  },
  {
    id: "amber-bottle",
    kind: "image",
    category: "Product",
    prompt:
      "An amber glass bottle on a seamless sand backdrop, hard side light, long clean shadow",
    modality: "IMAGE",
    width: 2048,
    height: 2048,
    poster: "/marketing/gallery/amber-bottle-1280.1481bebec1.webp",
    masterSha256:
      "1481bebec11a0c457285864cb502b664fcad42a8c227606043467ef7b466ef9f",
  },
  {
    id: "ice-station",
    kind: "image",
    category: "Science fiction",
    prompt:
      "A lone research station on an ice plain under a ringed planet, cold blue light",
    modality: "IMAGE",
    width: 2752,
    height: 1536,
    poster: "/marketing/gallery/ice-station-1280.a87429c6c9.webp",
    masterSha256:
      "a87429c6c9fab934086caf61072f02a469a8e790f3c02065619884dc61081d56",
  },
  {
    id: "orbital-elevator",
    kind: "image",
    category: "Science fiction",
    prompt:
      "An orbital elevator seen from the base at dusk, warm ground haze fading into black sky",
    modality: "IMAGE",
    width: 1696,
    height: 2528,
    poster: "/marketing/gallery/orbital-elevator-1280.2a894a9cfb.webp",
    masterSha256:
      "2a894a9cfbccd38ceeca41e5e179b62ad2d92c780541fd51a78142a052aef248",
  },
  {
    id: "circuit-macro",
    kind: "image",
    category: "Technology",
    prompt:
      "A circuit board photographed as landscape, macro lens, teal solder mask and gold traces",
    modality: "IMAGE",
    width: 2752,
    height: 1536,
    poster: "/marketing/gallery/circuit-macro-1280.acd3b7032d.webp",
    masterSha256:
      "acd3b7032db4549a2df8a4c00fe62ae8f6fa7ba545fd2e13c90a7d5ca021155c",
  },
  {
    id: "camel-coat-walk",
    kind: "video",
    category: "Fashion",
    prompt:
      "Slow tracking shot alongside a model walking in a long camel coat down a sunlit colonnade",
    modality: "VIDEO",
    width: 1088,
    height: 1920,
    poster: "/marketing/gallery/camel-coat-walk-1280.195cfc442a.webp",
    src: "/marketing/gallery/camel-coat-walk.195cfc442a.mp4",
    masterSha256:
      "195cfc442a0cb2b8b7a2e3e943ffb12cc16da095f84dad3e91bd653333635638",
  },
  {
    id: "ink-bloom",
    kind: "video",
    category: "Abstract",
    prompt:
      "Ink dropped into water, blooming and folding in slow motion, deep indigo against white",
    modality: "VIDEO",
    width: 1920,
    height: 1088,
    poster: "/marketing/gallery/ink-bloom-1280.3841aa41f6.webp",
    src: "/marketing/gallery/ink-bloom.3841aa41f6.mp4",
    masterSha256:
      "3841aa41f6fde0d7ea3107e6945643ff1267944deda1a1dc37572838344169ec",
  },
  {
    id: "paper-boat-street",
    kind: "video",
    category: "Cinematic",
    prompt:
      "A paper boat drifting down a rain-slicked street at night, slow push in",
    modality: "VIDEO",
    width: 720,
    height: 1280,
    poster: "/marketing/gallery/paper-boat-street-1280.86a4f5fcf0.webp",
    src: "/marketing/gallery/paper-boat-street.86a4f5fcf0.mp4",
    masterSha256:
      "86a4f5fcf08cc18de511e7e80fd114f879cc1ee3cf85a82f13dba0c242870132",
  },
  {
    id: "room-at-dusk",
    kind: "video",
    category: "Interior",
    prompt:
      "A darkened living room lit only by a large screen, warm light spilling across a sofa",
    modality: "VIDEO",
    width: 1920,
    height: 1088,
    poster: "/marketing/gallery/room-at-dusk-1280.b596527dcd.webp",
    src: "/marketing/gallery/room-at-dusk.b596527dcd.mp4",
    masterSha256:
      "b596527dcd5fef1f7210cdacd9f1a60395e54792c0f9e5fb869bdf07c1a55ba8",
  },
  {
    id: "display-macro",
    kind: "video",
    category: "Technology",
    prompt:
      "Extreme close-up of a bright display surface resolving into deep blacks and vivid highlights",
    modality: "VIDEO",
    width: 1920,
    height: 1088,
    poster: "/marketing/gallery/display-macro-1280.a481d515dc.webp",
    src: "/marketing/gallery/display-macro.a481d515dc.mp4",
    masterSha256:
      "a481d515dc03c51c4c0bc5f8a764adb4a6e39744ba13693b81b1d7fd8309f7fd",
  },
  {
    id: "coast-drive",
    kind: "video",
    category: "Automotive",
    prompt:
      "A photorealistic cinematic shot of a red convertible driving along a coastal road",
    modality: "VIDEO",
    width: 1280,
    height: 720,
    poster: "/marketing/gallery/coast-drive-1280.d92ff7a040.webp",
    src: "/marketing/gallery/coast-drive.d92ff7a040.mp4",
    masterSha256:
      "d92ff7a0406c7a51fc99df3d12ae642fd6c5435724603fc92d1d59b4754402b5",
  },
  {
    id: "dragon-tower",
    kind: "video",
    category: "Fantasy",
    prompt:
      "A red dragon on a castle throwing fire from its mouth, cinematic lighting, anamorphic",
    modality: "VIDEO",
    width: 1280,
    height: 720,
    poster: "/marketing/gallery/dragon-tower-1280.9282f7c982.webp",
    src: "/marketing/gallery/dragon-tower.9282f7c982.mp4",
    masterSha256:
      "9282f7c982c24fdbdf297846c00b9168f8e86df2def13672558558b7622d8e9a",
  },
  {
    id: "dragon-modern",
    kind: "video",
    category: "Fantasy",
    prompt:
      "A dragon on top of a castle breathing fire, modern and highly detailed",
    modality: "VIDEO",
    width: 1280,
    height: 720,
    poster: "/marketing/gallery/dragon-modern-1280.39377ddea0.webp",
    src: "/marketing/gallery/dragon-modern.39377ddea0.mp4",
    masterSha256:
      "39377ddea08a69d667b198cfa731d3026cf747d1f206f7ef8d02a13a53c1b18e",
  },
  {
    id: "coffee-dawn",
    kind: "video",
    category: "Lifestyle",
    prompt:
      "A single slow push-in on a cup of coffee steaming on a windowsill at dawn",
    modality: "VIDEO",
    width: 1280,
    height: 720,
    poster: "/marketing/gallery/coffee-dawn-1280.a434df0eb5.webp",
    src: "/marketing/gallery/coffee-dawn.a434df0eb5.mp4",
    masterSha256:
      "a434df0eb51c7c0b6543d8a21532c12b78ee447ffc79182805fd7a8df8292842",
  },
  {
    id: "four-shot-cut",
    kind: "video",
    category: "Sequence",
    prompt:
      "An edited sequence containing exactly four separate shots and three unmistakable cuts",
    modality: "VIDEO",
    width: 1280,
    height: 720,
    poster: "/marketing/gallery/four-shot-cut-1280.ec50228c6d.webp",
    src: "/marketing/gallery/four-shot-cut.ec50228c6d.mp4",
    masterSha256:
      "ec50228c6d02f8360e3e88c30253b425fa0d63b74ff4a41b04ab0d2a374f5f27",
  },
] as const;
