// Generated by scripts/build-gallery-media.mjs. Do not edit by hand.
//
// Every entry is derived from a master in `media-source/`: the dimensions are
// probed, the filenames carry the master's content hash, and the prompt is the
// one that produced it. Re-run the script after changing
// `media-source/gallery-selection.json`.

export interface GalleryItem {
  /** Stable slug. Also the filename stem, so it must stay unique. */
  id: string;
  kind: "image" | "video";
  /** Shown on the card, and the label the filters group by. */
  category: string;
  /** The prompt that made it. Shown under the card. */
  prompt: string;
  /** What "Try this" opens the studio in. */
  modality: "IMAGE" | "VIDEO";
  /** The master's real pixels, used for the aspect box so nothing shifts. */
  width: number;
  height: number;
  /** 1280w WebP. `next/image` resizes down from this for smaller cards. */
  poster: string;
  /** Videos only. Loaded on interaction, never before. */
  src?: string;
  /** The master this was derived from, recorded in docs/GALLERY-PROVENANCE.md. */
  masterSha256: string;
}

export const GALLERY: readonly GalleryItem[] = [
  {
    id: "paper-boat-street",
    kind: "video",
    category: "Cinematic",
    prompt:
      "A paper boat drifting down a rain-slicked street at night, slow push in",
    modality: "VIDEO",
    width: 720,
    height: 1280,
    poster: "/marketing/gallery/paper-boat-street-1280.86a4f5fcf0.webp",
    src: "/marketing/gallery/paper-boat-street.86a4f5fcf0.mp4",
    masterSha256:
      "86a4f5fcf08cc18de511e7e80fd114f879cc1ee3cf85a82f13dba0c242870132",
  },
  {
    id: "coast-drive",
    kind: "video",
    category: "Automotive",
    prompt:
      "A photorealistic cinematic shot of a red convertible driving along a coastal road",
    modality: "VIDEO",
    width: 1280,
    height: 720,
    poster: "/marketing/gallery/coast-drive-1280.d92ff7a040.webp",
    src: "/marketing/gallery/coast-drive.d92ff7a040.mp4",
    masterSha256:
      "d92ff7a0406c7a51fc99df3d12ae642fd6c5435724603fc92d1d59b4754402b5",
  },
  {
    id: "dragon-modern",
    kind: "video",
    category: "Fantasy",
    prompt:
      "A dragon on top of a castle breathing fire, modern and highly detailed",
    modality: "VIDEO",
    width: 1280,
    height: 720,
    poster: "/marketing/gallery/dragon-modern-1280.39377ddea0.webp",
    src: "/marketing/gallery/dragon-modern.39377ddea0.mp4",
    masterSha256:
      "39377ddea08a69d667b198cfa731d3026cf747d1f206f7ef8d02a13a53c1b18e",
  },
  {
    id: "coffee-dawn",
    kind: "video",
    category: "Lifestyle",
    prompt:
      "A single slow push-in on a cup of coffee steaming on a windowsill at dawn",
    modality: "VIDEO",
    width: 1280,
    height: 720,
    poster: "/marketing/gallery/coffee-dawn-1280.a434df0eb5.webp",
    src: "/marketing/gallery/coffee-dawn.a434df0eb5.mp4",
    masterSha256:
      "a434df0eb51c7c0b6543d8a21532c12b78ee447ffc79182805fd7a8df8292842",
  },
] as const;
