import { describe, expect, it } from "vitest";

import {
  AUDIO_CAPABILITIES,
  buildAudioDirection,
  quoteAudio,
  resolveAudioStrategy,
  SOUND_DESIGN_PROVIDER,
  type AudioStrategy,
} from "@/services/ai/audio-strategy";
import { runAudioGate, settleGeneration } from "@/services/video/audio-gate";

/**
 * Audio, end to end.
 *
 * ## What went wrong
 *
 * Atheos shipped video with no audio stream while the composer displayed
 * "Soundscape added by Atheos". That label described a pipeline nobody had
 * built — Motion 1 and Motion Pro have no audio field in their schemas, and no
 * post step added one. The user was quoted for sound and received silence.
 *
 * These tests hold the three things that stops recurring: a model can only be
 * offered what it declares, added sound is never called native, and a promise
 * of audio that the file does not contain fails delivery and settles nothing.
 */

const MOTION_1 = AUDIO_CAPABILITIES["replicate/video-gen"];
const MOTION_PRO = AUDIO_CAPABILITIES["replicate/video-pro"];
const CINEMATIC_FAST = AUDIO_CAPABILITIES["replicate/veo-3.1-fast"];
const CINEMATIC_LITE = AUDIO_CAPABILITIES["replicate/veo-3.1-lite"];
/**
 * "Cinematic Long" (`seedance-2.5`) was removed with the rest of that phantom:
 * it had an audio strategy, a routing row and a compiler, and no registry entry
 * at all, so nothing could ever run it. See the TODO in `audio-strategy.ts`.
 */
const CINEMATIC = AUDIO_CAPABILITIES["replicate/veo-3.1"];

const GOOD_AUDIO = {
  hasStream: true,
  codec: "aac",
  sampleRate: 48_000,
  channels: 2,
  durationSeconds: 8,
  integratedLufs: -16,
  truePeakDb: -1.2,
  longestSilenceSeconds: 0.3,
};

const PROMISED = {
  strategy: "NATIVE" as AudioStrategy,
  videoDurationSeconds: 8,
  allowSpeech: false,
  allowMusic: false,
};

describe("1. every video model declares an audio strategy", () => {
  it("declares at least one, for all five tiers", () => {
    // Five, not six: the sixth was `seedance-2.5`, which no adapter served.
    const ids = Object.keys(AUDIO_CAPABILITIES);
    expect(ids.length).toBeGreaterThanOrEqual(5);
    for (const id of ids) {
      const model = AUDIO_CAPABILITIES[id];
      expect(model.strategies.length, id).toBeGreaterThan(0);
      expect(model.note, id).toBeTruthy();
    }
  });

  it("uses only the three defined strategies", () => {
    const allowed = new Set(["NATIVE", "ATHEOS_SOUND_DESIGN", "SILENT"]);
    for (const model of Object.values(AUDIO_CAPABILITIES)) {
      for (const s of model.strategies) expect(allowed.has(s), s).toBe(true);
    }
  });
});

describe("2. Motion 1 never claims native audio", () => {
  it("declares no native strategy", () => {
    // wan-2.2-t2v-fast has no audio field of any kind in its schema.
    expect(MOTION_1.strategies).not.toContain("NATIVE");
    expect(MOTION_1.note).toMatch(/produces no audio/);
  });

  it("resolves to Atheos sound design, labelled as added", () => {
    const r = resolveAudioStrategy({ model: MOTION_1, wantsSound: true });
    expect(r.strategy).toBe("ATHEOS_SOUND_DESIGN");
    // The exact wording the product must never shorten to "audio generated".
    expect(r.label).toBe("Atheos sound design added after generation");
    expect(r.label).not.toMatch(/native/i);
  });

  it("applies the same to Motion Pro, which was audited the same way", () => {
    expect(MOTION_PRO.strategies).not.toContain("NATIVE");
    expect(
      resolveAudioStrategy({ model: MOTION_PRO, wantsSound: true }).strategy,
    ).toBe("ATHEOS_SOUND_DESIGN");
  });
});

describe("3-4. quoting the audio stage", () => {
  it("quotes an added cost and extra time for sound design", () => {
    const q = quoteAudio({
      strategy: "ATHEOS_SOUND_DESIGN",
      durationSeconds: 8,
    });
    expect(q.providerCalls).toBe(1);
    expect(q.providerCostMicroUsd).toBe(4_900);
    expect(q.additionalCredits).toBeGreaterThan(0);
    expect(q.additionalSeconds).toBe(5);
    // The disclosure the composer owes the user, in the quote itself.
    expect(q.disclosure).toMatch(/generated by Atheos from the finished video/);
  });

  it("charges nothing extra for native audio", () => {
    const q = quoteAudio({ strategy: "NATIVE", durationSeconds: 8 });
    expect(q.providerCalls).toBe(0);
    expect(q.additionalCredits).toBe(0);
    expect(q.additionalSeconds).toBe(0);
  });

  it("silent mode costs nothing and calls no audio provider", () => {
    const q = quoteAudio({ strategy: "SILENT", durationSeconds: 8 });
    expect(q.providerCalls).toBe(0);
    expect(q.providerCostMicroUsd).toBe(0);
    expect(q.additionalCredits).toBe(0);
  });
});

describe("5. native models do not invoke the added-audio provider", () => {
  it("resolves native and quotes zero extra calls", () => {
    for (const model of [CINEMATIC_FAST, CINEMATIC]) {
      const r = resolveAudioStrategy({ model, wantsSound: true });
      expect(r.strategy, model.label).toBe("NATIVE");
      expect(
        quoteAudio({ strategy: r.strategy, durationSeconds: 8 }).providerCalls,
      ).toBe(0);
    }
  });
});

describe("18. silent stays available, except where the model cannot", () => {
  it("offers silent on models that support it", () => {
    const r = resolveAudioStrategy({ model: MOTION_1, wantsSound: false });
    expect(r.strategy).toBe("SILENT");
    expect(r.overridden).toBe(false);
  });

  it("says so plainly when a model cannot be silenced", () => {
    /**
     * Cinematic Lite's schema has no `generate_audio` field, so a Silent switch
     * on that tier would be wired to nothing. The resolver reports the override
     * instead of pretending the request was honoured.
     */
    const r = resolveAudioStrategy({
      model: CINEMATIC_LITE,
      wantsSound: false,
    });
    expect(r.strategy).toBe("NATIVE");
    expect(r.overridden).toBe(true);
    expect(r.label).toMatch(/always generates sound/);
  });
});

describe("the selected sound-design provider", () => {
  it("takes the completed video, a direction and a negative prompt", () => {
    /**
     * The sprint's own rule: a generic text-to-music model is not synchronised
     * sound design. MMAudio conditions on the finished file.
     */
    expect(SOUND_DESIGN_PROVIDER.modelId).toBe("zsxkib/mmaudio");
    expect(SOUND_DESIGN_PROVIDER.acceptsCompletedVideo).toBe(true);
    expect(SOUND_DESIGN_PROVIDER.acceptsDirectionPrompt).toBe(true);
    // Without this, "no music" cannot be enforced — which is why thinksound
    // was not selected.
    expect(SOUND_DESIGN_PROVIDER.acceptsNegativePrompt).toBe(true);
  });

  it("records where its price came from", () => {
    expect(SOUND_DESIGN_PROVIDER.perRunUsd).toBe(0.0049);
    expect(SOUND_DESIGN_PROVIDER.costBasis).toMatch(/read 2026-08-23/);
  });
});

describe("audio direction is derived from the scene, not hardcoded", () => {
  it("uses the user's own scene", () => {
    const d = buildAudioDirection({
      scene: "a chef searing steak in a loud restaurant kitchen",
      preset: "natural",
    });
    expect(d.prompt).toContain("searing steak");
    // The red-car wording is an example of output, not a fixture. A hardcoded
    // coastal prompt would put engine noise under a kitchen.
    expect(d.prompt).not.toMatch(/engine|ocean|surf|convertible/i);
  });

  it("forbids speech and music by default, in the negative prompt", () => {
    const d = buildAudioDirection({
      scene: "a red convertible on a coast road",
      preset: "natural",
    });
    expect(d.negativePrompt).toContain("music");
    expect(d.negativePrompt).toContain("dialogue");
    expect(d.allowMusic).toBe(false);
    expect(d.allowSpeech).toBe(false);
  });

  it("mentions cut continuity only when the video actually has cuts", () => {
    const withCuts = buildAudioDirection({
      scene: "a red convertible on a coast road",
      preset: "cinematic",
      cutTimestamps: [2, 4, 6],
    });
    expect(withCuts.prompt).toMatch(/unbroken across the cuts/);

    const noCuts = buildAudioDirection({
      scene: "a red convertible on a coast road",
      preset: "cinematic",
      cutTimestamps: [],
    });
    // Instructing a model about cuts that are not in the file it is looking at.
    expect(noCuts.prompt).not.toMatch(/across the cuts/);
  });

  it("targets web loudness", () => {
    const d = buildAudioDirection({ scene: "x", preset: "natural" });
    expect(d.targetLufs).toBe(-16);
    expect(d.truePeakDb).toBe(-1);
  });
});

describe("6, 9, 10. the audio gate", () => {
  it("passes compliant audio", () => {
    const r = runAudioGate({ measured: GOOD_AUDIO, promised: PROMISED });
    expect(r.outcome).toBe("pass");
    expect(r.deliverWithAudio).toBe(true);
    expect(r.settleAudioCredits).toBe(true);
  });

  it("fails a missing stream when audio was promised", () => {
    const r = runAudioGate({
      measured: { hasStream: false },
      promised: PROMISED,
    });
    expect(r.outcome).toBe("fail");
    expect(r.settleAudioCredits).toBe(false);
    expect(r.failures.join(" ")).toMatch(/no audio stream/);
  });

  it("fails digital silence", () => {
    const r = runAudioGate({
      measured: { ...GOOD_AUDIO, integratedLufs: -80 },
      promised: PROMISED,
    });
    expect(r.failures.join(" ")).toMatch(/digital silence/);
  });

  it("fails unmeasurable loudness rather than assuming it is fine", () => {
    // NaN is the hole that let a file through the video gate: `??` misses it
    // and every comparison against it is false.
    for (const lufs of [undefined, Number.NaN]) {
      const r = runAudioGate({
        measured: { ...GOOD_AUDIO, integratedLufs: lufs },
        promised: PROMISED,
      });
      expect(r.outcome, String(lufs)).toBe("fail");
      expect(r.failures.join(" ")).toMatch(/could not be measured/);
    }
  });

  it("fails clipping", () => {
    const r = runAudioGate({
      measured: { ...GOOD_AUDIO, truePeakDb: 0.8 },
      promised: PROMISED,
    });
    expect(r.failures.join(" ")).toMatch(/clipping/);
  });

  it("fails an undecodable file", () => {
    const r = runAudioGate({
      measured: { hasStream: true, decodeError: "moov atom not found" },
      promised: PROMISED,
    });
    expect(r.failures.join(" ")).toMatch(/could not be decoded/);
  });

  it("fails an unsupported codec", () => {
    const r = runAudioGate({
      measured: { ...GOOD_AUDIO, codec: "wmav2" },
      promised: PROMISED,
    });
    expect(r.failures.join(" ")).toMatch(/not supported for delivery/);
  });
});

describe("8. audio and video duration must match", () => {
  it("fails audio shorter than the video", () => {
    const r = runAudioGate({
      measured: { ...GOOD_AUDIO, durationSeconds: 6.5 },
      promised: PROMISED,
    });
    expect(r.failures.join(" ")).toMatch(/1.500s shorter than the video/);
  });

  it("fails audio longer than the video", () => {
    const r = runAudioGate({
      measured: { ...GOOD_AUDIO, durationSeconds: 9.2 },
      promised: PROMISED,
    });
    expect(r.failures.join(" ")).toMatch(/1.200s longer than the video/);
  });

  it("tolerates a container ending a few milliseconds late", () => {
    const r = runAudioGate({
      measured: { ...GOOD_AUDIO, durationSeconds: 8.02 },
      promised: PROMISED,
    });
    expect(r.outcome).toBe("pass");
  });
});

describe("13-14. audio failure never remakes the video", () => {
  const failed = runAudioGate({
    measured: { hasStream: false },
    promised: { ...PROMISED, strategy: "ATHEOS_SOUND_DESIGN" },
  });

  it("preserves the video and refuses to regenerate it", () => {
    /**
     * The video costs dollars and minutes; the sound costs half a cent. Throwing
     * away a good picture because the cheap stage failed is the expensive
     * mistake.
     */
    expect(failed.preserveVideo).toBe(true);
    expect(failed.regenerateVideo).toBe(false);
  });

  it("offers a quoted audio-only retry rather than taking one", () => {
    expect(failed.offerQuotedAudioRetry).toBe(true);
    // Offered. Nothing here spends money.
    expect(failed.settleAudioCredits).toBe(false);
  });

  it("does not offer a retry when the failure was native audio", () => {
    // A native failure means the whole generation came back wrong; retrying the
    // audio alone is not a thing that exists.
    const nativeFail = runAudioGate({
      measured: { hasStream: false },
      promised: PROMISED,
    });
    expect(nativeFail.offerQuotedAudioRetry).toBe(false);
  });
});

describe("silent delivery is correct, not an audio pass", () => {
  it("reports not_promised rather than pass", () => {
    const r = runAudioGate({
      measured: { hasStream: false },
      promised: { ...PROMISED, strategy: "SILENT" },
    });
    expect(r.outcome).toBe("not_promised");
    expect(r.failures).toHaveLength(0);
    expect(r.settleAudioCredits).toBe(false);
    expect(r.label).toBe("Silent video");
  });

  it("warns when a silent export somehow has a stream", () => {
    const r = runAudioGate({
      measured: GOOD_AUDIO,
      promised: { ...PROMISED, strategy: "SILENT" },
    });
    expect(r.warnings.join(" ")).toMatch(
      /silent export contains an audio stream/,
    );
  });
});

describe("12, 15, 16, 17. accounting", () => {
  const common = {
    videoProvider: "replicate/video-gen",
    audioProvider: "zsxkib/mmaudio",
    videoEstimatedMicroUsd: 100_000,
    audioEstimatedMicroUsd: 4_900,
    strategy: "ATHEOS_SOUND_DESIGN" as AudioStrategy,
    quotedVideoCredits: 90,
    quotedAudioCredits: 3,
  };

  it("includes the audio cost in the single quoted number", () => {
    const a = settleGeneration({
      ...common,
      videoPassed: true,
      audioOutcome: "pass",
    });
    expect(a.quotedCredits).toBe(93);
    expect(a.reservedCredits).toBe(93);
    expect(a.settledCredits).toBe(93);
    expect(a.releasedCredits).toBe(0);
  });

  it("settles the video and releases the audio when audio fails", () => {
    const a = settleGeneration({
      ...common,
      videoPassed: true,
      audioOutcome: "fail",
    });
    expect(a.settledCredits).toBe(90);
    expect(a.releasedCredits).toBe(3);
    // Reserved always equals settled plus released — no ledger drift.
    expect(a.settledCredits + a.releasedCredits).toBe(a.reservedCredits);
  });

  it("releases everything when the video itself failed", () => {
    const a = settleGeneration({
      ...common,
      videoPassed: false,
      audioOutcome: "fail",
    });
    expect(a.settledCredits).toBe(0);
    expect(a.releasedCredits).toBe(93);
  });

  it("cannot bill twice for the same completion", () => {
    // Settlement is a pure function of the outcomes, so a duplicate webhook
    // computes the same number rather than adding a second charge.
    const once = settleGeneration({
      ...common,
      videoPassed: true,
      audioOutcome: "pass",
    });
    const twice = settleGeneration({
      ...common,
      videoPassed: true,
      audioOutcome: "pass",
    });
    expect(twice).toEqual(once);
  });

  it("deducts zero customer credits for an internal benchmark", () => {
    const a = settleGeneration({
      ...common,
      videoPassed: true,
      audioOutcome: "pass",
      isInternalBenchmark: true,
      videoActualMicroUsd: 3_200_000,
    });
    expect(a.customerCreditsDeducted).toBe(0);
    // The provider cost is still recorded — the money was real.
    expect(a.video.actualMicroUsd).toBe(3_200_000);
    expect(a.isInternalBenchmark).toBe(true);
  });

  it("records each stage's provider and cost separately", () => {
    const a = settleGeneration({
      ...common,
      videoPassed: true,
      audioOutcome: "pass",
      videoActualMicroUsd: 108_000,
      audioActualMicroUsd: 4_700,
    });
    expect(a.video.provider).toBe("replicate/video-gen");
    expect(a.audio?.provider).toBe("zsxkib/mmaudio");
    expect(a.video.actualMicroUsd).toBe(108_000);
    expect(a.audio?.actualMicroUsd).toBe(4_700);
  });

  it("omits the audio stage entirely for a native generation", () => {
    const a = settleGeneration({
      videoPassed: true,
      audioOutcome: "pass",
      quotedVideoCredits: 576,
      quotedAudioCredits: 0,
      videoProvider: "replicate/veo-3.1-fast",
      videoEstimatedMicroUsd: 1_200_000,
      strategy: "NATIVE",
    });
    expect(a.audio).toBeUndefined();
    expect(a.quotedCredits).toBe(576);
  });
});

describe("20. no paid provider call occurs in these tests", () => {
  it("uses only pure functions and literals", () => {
    /**
     * Stated as a test because it is the constraint most easily broken by a
     * later edit. Every module under test here is pure: nothing in this file
     * reaches a network, and the provider constants are read, never called.
     */
    expect(SOUND_DESIGN_PROVIDER.modelId).toBe("zsxkib/mmaudio");
    expect(typeof quoteAudio).toBe("function");
    expect(typeof runAudioGate).toBe("function");
  });
});
